* Encoding: UTF-8.
file handle data /name="c:/spss23/samples/english/employee data.sav".
get file="data".
dataset name emp.
compute id = -id.
STATS C50 TREE DEPENDENT=jobcat independent=jobtime prevexp educ ID=id
/OPTIONS MISSING=INCLUDE FACTORCONVERSION=LEVELS BOOSTS=1 FEATURESELECTION=NO
confidence=25 MINSIZE=2 TRAINPROP=0 
/PRINT TREE=YES RULES=NO COSTMATRIX=YES VARIMPORTANCE=YES
/SAVE WORKSPACEACTION=CLEAR PREDTYPE=CLASS.

STATS C50 TREE DEPENDENT=jobcat independent=jobtime prevexp educ ID=id 
/OPTIONS MISSING=INCLUDE FACTORCONVERSION=LEVELS BOOSTS=1 FEATURESELECTION=NO
confidence=25 MINSIZE=2 TRAINPROP=0 
/PRINT TREE=YES RULES=NO COSTMATRIX=YES VARIMPORTANCE=YES
/SAVE WORKSPACEACTION=CLEAR DATASET=pred PREDTYPE=CLASS.

DATASET ACTIVATE emp.
STATS C50 TREE DEPENDENT=jobcat independent=jobtime prevexp educ 
/OPTIONS MISSING=INCLUDE FACTORCONVERSION=LEVELS BOOSTS=3 FEATURESELECTION=NO
confidence=25 MINSIZE=2 TRAINPROP=0 
/PRINT TREE=YES RULES=YES COSTMATRIX=YES VARIMPORTANCE=YES
/SAVE WORKSPACEACTION=RETAIN DATASET=pred PREDTYPE=PROB.

STATS C50 TREE DEPENDENT=jobcat independent=jobtime prevexp educ salary 
/OPTIONS MISSING=INCLUDE FACTORCONVERSION=LEVELS BOOSTS=3 FEATURESELECTION=NO
confidence=25 MINSIZE=2 TRAINPROP=0 
/PRINT TREE=YES RULES=YES COSTMATRIX=YES VARIMPORTANCE=YES
/SAVE WORKSPACEACTION=RETAIN DATASET=pred PREDTYPE=PROB.



STATS C50 TREE MODE=PREDICT USEWORKSPACE=YES 
/OPTIONS MISSING=INCLUDE FACTORCONVERSION=LEVELS BOOSTS=3 FEATURESELECTION=NO
confidence=25 MINSIZE=2 TRAINPROP=0 
/PRINT TREE=NO RULES=YES COSTMATRIX=YES VARIMPORTANCE=YES
/SAVE WORKSPACEACTION=RETAIN DATASET=predfromretain PREDTYPE=PROB.

* make independent variables inconsistent.
variable level educ minority(scale).
STATS C50 TREE DEPENDENT=jobcat independent=jobtime prevexp educ minority
/save workspaceaction=retain.
variable level educ minority(nominal).
STATS C50 TREE MODE=PREDICT USEWORKSPACE=YES
/SAVE WORKSPACEACTION=RETAIN DATASET=predfromretain.

* trainfrac.
STATS C50 TREE MODE=ESTIMATE DEPENDENT=jobcat independent=minority prevexp gender salary 
/OPTIONS MISSING=INCLUDE FACTORCONVERSION=LEVELS BOOSTS=1 FEATURESELECTION=NO
confidence=25 MINSIZE=2 TRAINPROP=0.
STATS C50 TREE MODE=ESTIMATE DEPENDENT=jobcat independent=minority prevexp gender salary 
/OPTIONS MISSING=INCLUDE FACTORCONVERSION=LEVELS BOOSTS=3 FEATURESELECTION=NO
confidence=25 MINSIZE=2 TRAINPROP=.25 .

STATS C50 TREE MODE=ESTIMATE DEPENDENT=jobcat independent=minority prevexp gender salary 
/OPTIONS MISSING=INCLUDE FACTORCONVERSION=LEVELS BOOSTS=3 FEATURESELECTION=NO
confidence=25 MINSIZE=2 TRAINPROP=.70. 


STATS C50 TREE MODE=ESTIMATE DEPENDENT=jobcat independent=minority prevexp gender salary 
/OPTIONS MISSING=INCLUDE FACTORCONVERSION=LEVELS BOOSTS=1 FEATURESELECTION=NO
confidence=25 MINSIZE=2 TRAINPROP=.999 
/PRINT TREE=YES RULES=YES COSTMATRIX=NO VARIMPORTANCE=NO rulebands=2
/SAVE WORKSPACEACTION=RETAIN PREDTYPE=PROB.
